global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: homelab-scrapes
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'grafana:3000'
          - 'traefik:8080'

  - job_name: 'teamcity'
    metrics_path: '/app/metrics'
    params:
      experimental: ['true']
    scheme: http
    bearer_token: 'TOKEN'
    static_configs:
    - targets: [
      '192.168.1.teamcity-ip:8111'
    ]

  - job_name: 'gitlab'
    metrics_path: /-/metrics
    scheme: http
    params:
      token: ['get-token-from-gitlab-health']
    static_configs:
      - targets: [
        '192.168.1.gitlab-ip:8081'
    ]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [
          'alertmanager:9093'
        ]