global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - "prometheus_rules.yml"
  # - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - '192.168.1.101:9090'

  - job_name: 'teamcity'
    metrics_path: '/app/metrics'
    params:
      experimental: ['true']
    scheme: http
    bearer_token: 'TOKEN'
    static_configs:
    - targets: [
      '192.168.1.101:8111'
    ]